name: example-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - plotly
  - pandas
  - matplotlib
  - scikitlearn
  - numpy
  - r-base=4.0
  - dplyr
  - ggplot2
  - reshape2
  - tidyverse
  - plotly
  - stringr
