name: example-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - plotly
  - pandas
  - matplotlib
  - scikitlearn
  - numpy
  - r-base=4.0
  - r-dpylyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotly
  - r-stringr
